[package]
name = "assets"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
anyhow.workspace = true
log.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rust-embed.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
futures.workspace = true
reqwest = { version = "0.12", default-features = false }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Location"] }
