[package]
name = "nip29_ui"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chat = { path = "../chat" }
chat_ui = { path = "../chat_ui" }
common = { path = "../common" }
nip29 = { path = "../nip29" }
person = { path = "../person" }
settings = { path = "../settings" }
state = { path = "../state" }
theme = { path = "../theme" }
ui = { path = "../ui" }

gpui.workspace = true
nostr-sdk.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true
smallvec.workspace = true
