[package]
name = "auto_update"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
instant.workspace = true
log.workspace = true

gpui-updater = { git = "https://github.com/AprilNEA/gpui-updater", tag = "v0.0.6", features = ["gpui"] }
