[package]
name = "auto_update"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
instant.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true

gpui-updater-core = { git = "https://github.com/AprilNEA/gpui-updater" }
