[package]
name = "concord"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
nostr.workspace = true
nostr-sdk.workspace = true

hkdf.workspace = true
sha2.workspace = true
chacha20.workspace = true
hmac.workspace = true
data-encoding.workspace = true
base64.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[dev-dependencies]
smol.workspace = true
